language: python

python:
  - "3.6"

service:
  - postgresql

install:
  - pip install -r requirements.txt

before_script:
  - export APP_SETTINGS="app.config.TestingConfig"
  - export DATABASE_URL=postgresql://postgres:@localhost/u
  - psql -c 'create database users;' -U postgres

script:
  - python manage.py test
